### ISSUE TITLE
Verify need to update implementation reports

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-star#231]
@gkellogg to Re-run EARL scripts on previously removed implementation reports (EYE and Jena) and report back on reasons for re-submission.

cc/ @afs @josd

**Comment by gkellogg** [comment]
Running the earl-report tool independently on the old Jena and EYE reports, I get the following warnings, which prevent the report from completing.

Running `earl-report --format json --strict ./jena-report-2021-06-06.ttl`

```
Skipping result for https://w3c.github.io/rdf-star/tests/trig/eval#trig-star-embed-annotation-2 for http://jena.apache.org/#jena, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/trig/eval#trig-star-embed-annotation-1 for http://jena.apache.org/#jena, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/turtle/eval#turtle-star-embed-annotation-2 for http://jena.apache.org/#jena, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/turtle/eval#turtle-star-embed-annotation-3 for http://jena.apache.org/#jena, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/trig/eval#trig-star-embed-annotation-3 for http://jena.apache.org/#jena, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/turtle/eval#turtle-star-embed-annotation-1 for http://jena.apache.org/#jena, which is not defined in manifests
/Users/gregg/.rvm/gems/ruby-3.0.2/gems/earl-report-0.7.0/lib/earl_report.rb:452:in `initialize': Warnings issued in strict mode (RuntimeError)
```

Running `earl-report --format json --strict ./eye-earl.ttl`

```
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#constrained-bnodes-in-embedded-subject for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#bnodes-in-embedded-subject-and-object for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#all-identical-embedded-triples-are-the-same for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#constrained-bnodes-in-embedded-fail for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#bnodes-in-embedded-subject-and-object-fail for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#same-bnode-same-embedded-term for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#constrained-bnodes-in-embedded-object for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#embedded-triples-no-spurious for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/turtle/eval#turtle-star-embed-annotation-1 for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/turtle/eval#turtle-star-embed-annotation-3 for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/turtle/eval#turtle-star-embed-annotation-2 for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#different-bnodes-same-embedded-term for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#bnodes-in-embedded-object for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#embedded-not-asserted for https://josd.github.io/eye/, which is not defined in manifests
Skipping result for https://w3c.github.io/rdf-star/tests/semantics#bnodes-in-embedded-subject for https://josd.github.io/eye/, which is not defined in manifests
/Users/gregg/.rvm/gems/ruby-3.0.2/gems/earl-report-0.7.0/lib/earl_report.rb:452:in `initialize': Warnings issued in strict mode (RuntimeError)
```

In both cases, re-running the test suite to create a new earl submission should fix the problem. The PR will re-run the scripts and report if there are any remaining errors.

**Comment by josd** [comment]
PR https://github.com/w3c/rdf-star/pull/232 looks fine and also reflects the latest state.
